### ISSUE TITLE
elder mottled boar is recognized as a boss (auto dkp award)

### ISSUE THREAD

**Issue by knasen88** [DuduSandsten/WebDKP#3]
Hi, currently Elder mottled boar (the ones outside orgrimmar all are counted by auto dkp award so whenever one is killed the raid get +5 dkp(or whatever number u put). how do i fix this? i cant see what lua recognizes bosses or anything.

**Comment by DuduSandsten** [comment]
This is used for testing. I will remove it next update. For now if it bothers you edit this line 
https://github.com/DuduSandsten/WebDKP/blob/master/WebDKP.lua#L147

From:
test_loc = Set {"Elder Mottled Boar"}

To:
test_loc = Set {"there is no npc in the game with this name"}

**Comment by DuduSandsten** [comment]
New version supports giving out percentage decay instead of flat value decay.
I also removed the Elder Mottled Boar so if you get the latest it should be good now :)
